Repository kiosk-team-04/kiosk-max, pull requests merged in 2023-06, with the labels that each got.

#3 [fe] chore: 초기 설정 세팅
  fe/.eslintrc.json
  fe/.gitignore
  fe/.prettierrc
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.jsx
  fe/src/App.module.css
  fe/src/index.css
  fe/src/index.jsx
  fe/src/reportWebVitals.jsx
  fe/src/setupTests.jsx
Labels: front-end, setting

#8 [be] chore: 프로젝트 생성
  .idea/.gitignore
  .idea/Kiosk-Project.iml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  docker.yml
  kiosk-be/.gitignore
  kiosk-be/build.gradle
  kiosk-be/gradle/wrapper/gradle-wrapper.jar
  kiosk-be/gradle/wrapper/gradle-wrapper.properties
  kiosk-be/gradlew
  kiosk-be/gradlew.bat
  kiosk-be/settings.gradle
  kiosk-be/src/main/java/team04/kioskbe/KioskBeApplication.java
  kiosk-be/src/main/resources/application-db.yml
  kiosk-be/src/main/resources/application.yml
  kiosk-be/src/main/resources/schema.sql
  kiosk-be/src/test/java/team04/kioskbe/KioskBeApplicationTests.java
Labels: back-end, setting

#9 [be] chore: 프로젝트 초기 설정
  .idea/.gitignore
  .idea/Kiosk-Project.iml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  docker.yml
  kiosk-be/.gitignore
  kiosk-be/build.gradle
  kiosk-be/gradle/wrapper/gradle-wrapper.jar
  kiosk-be/gradle/wrapper/gradle-wrapper.properties
  kiosk-be/gradlew
  kiosk-be/gradlew.bat
  kiosk-be/settings.gradle
  kiosk-be/src/main/java/team04/kioskbe/KioskBeApplication.java
  kiosk-be/src/main/resources/application-db.yml
  kiosk-be/src/main/resources/application.yml
  kiosk-be/src/main/resources/schema.sql
  kiosk-be/src/test/java/team04/kioskbe/KioskBeApplicationTests.java
Labels: back-end, setting

#14 [be] feat: open API 파일 작성
  .gitignore
  openAPI.yml
Labels: back-end, feat

#17 [fe] design: 메인화면 UI 구현
  fe/src/App.jsx
  fe/src/App.module.css
  fe/src/components/CategoryTab/CategoryTab.jsx
  fe/src/components/CategoryTab/CategoryTab.module.css
  fe/src/components/Menu/MenuItem.jsx
  fe/src/components/Menu/MenuItem.module.css
  fe/src/components/Menu/MenuList.jsx
  fe/src/components/Menu/MenuList.module.css
Labels: front-end, design, review

#12 [fe] design: 메뉴 담기 창 UI 작업
  fe/src/components/Modal/Dim/Dim.jsx
  fe/src/components/Modal/Dim/Dim.module.css
  fe/src/components/Modal/Menu/Menu.jsx
  fe/src/components/Modal/Menu/Menu.module.css
Labels: front-end, design

#19 [be] docs: 변경된 요구사항에 따른 kiosk API 문서 수정
  openAPI.yml
Labels: back-end, docs, review

#21 [fe] feat: 카테고리 탭, 모달 기능
  fe/.eslintrc.json
  fe/package-lock.json
  fe/package.json
  fe/public/mockServiceWorker.js
  fe/src/App.jsx
  fe/src/components/CategoryTab/CategoryTab.jsx
  fe/src/components/CategoryTab/CategoryTab.module.css
  fe/src/components/Menu/MenuItem.jsx
  fe/src/components/Menu/MenuItem.module.css
  fe/src/components/Menu/MenuList.jsx
  fe/src/components/Modal/Dim/Dim.module.css
  fe/src/components/Modal/Menu/Decision/Decision.jsx
  fe/src/components/Modal/Menu/Decision/Decision.module.css
  fe/src/components/Modal/Menu/Info/Info.jsx
  fe/src/components/Modal/Menu/Info/Info.module.css
  fe/src/components/Modal/Menu/Menu.jsx
  fe/src/components/Modal/Menu/MenuModal.jsx
  fe/src/components/Modal/Menu/MenuModal.module.css
  fe/src/index.jsx
  fe/src/mocks/data/catagories.js
  fe/src/mocks/data/coffee.js
  fe/src/mocks/data/decaffein.js
  fe/src/mocks/data/juice.js
  fe/src/mocks/data/latte.js
  fe/src/mocks/data/tea.js
  fe/src/mocks/handlers.js
  fe/src/mocks/worker.js
Labels: front-end, feat, setting

#23 [be] feat: CI/CD 구현
  .github/workflows/cicd.yml
  .idea/gradle.xml
  kiosk-be/build.gradle
  kiosk-be/src/main/java/team04/kioskbe/HelloController.java
  kiosk-be/src/main/java/team04/kioskbe/MockController.java
  kiosk-be/src/main/resources/application-db.yml
  kiosk-be/src/main/resources/application.yml
  kiosk-be/src/main/resources/schema.sql
  kiosk-be/src/test/java/team04/kioskbe/KioskBeApplicationTests.java
Labels: back-end, setting

#24 [be] fix: Procfile 작성
  Procfile
Labels: back-end, fix

#25 [be] feat: 도메인 클래스 작성
  kiosk-be/.gitignore
  kiosk-be/src/main/java/team04/kioskbe/domain/Category.java
  kiosk-be/src/main/java/team04/kioskbe/domain/Drink.java
  kiosk-be/src/main/java/team04/kioskbe/domain/Option.java
  kiosk-be/src/main/java/team04/kioskbe/domain/Order.java
  kiosk-be/src/main/java/team04/kioskbe/domain/Payment.java
Labels: back-end, feat

#29 [fe] refactor: 메뉴 담기 창 리팩토링
  fe/src/App.jsx
  fe/src/components/Menu/MenuItem.module.css
  fe/src/components/Modal/Menu/Info/Info.jsx
  fe/src/mocks/data/catagories.js
  fe/src/mocks/data/coffee.js
  fe/src/mocks/data/decaffein.js
  fe/src/mocks/data/juice.js
  fe/src/mocks/data/latte.js
  fe/src/mocks/data/tea.js
Labels: front-end, review, refactor

#31 [be] feat: 카테고리 목록 조회
  kiosk-be/build.gradle
  kiosk-be/src/main/java/team04/kioskbe/Drink/CategoryResponse.java
  kiosk-be/src/main/java/team04/kioskbe/Drink/DrinkController.java
  kiosk-be/src/main/java/team04/kioskbe/Drink/DrinkService.java
  kiosk-be/src/main/java/team04/kioskbe/domain/Category.java
  kiosk-be/src/test/java/team04/kioskbe/Drink/DrinkServiceTest.java
Labels: back-end, feat

#32 [fe] feat: 메뉴 담겨진 화면 UI 및 기능
  fe/src/App.jsx
  fe/src/App.module.css
  fe/src/components/Cart/Cart.jsx
  fe/src/components/Cart/Cart.module.css
  fe/src/components/Cart/CartItem.jsx
  fe/src/components/Cart/CartItem.module.css
  fe/src/components/Cart/CartLists.jsx
  fe/src/components/Cart/CartLists.module.css
  fe/src/components/Menu/MenuItem.jsx
  fe/src/components/Menu/MenuList.jsx
  fe/src/components/Modal/Cancel/Cancel.jsx
  fe/src/components/Modal/Menu/Decision/Decision.jsx
  fe/src/components/Modal/Menu/Info/Info.jsx
  fe/src/components/Modal/Menu/MenuModal.jsx
  fe/src/mocks/data/decaffein.js
  fe/src/mocks/data/juice.js
  fe/src/mocks/data/latte.js
  fe/src/mocks/data/tea.js
Labels: front-end, feat, design

#35 [fe] feat: 결제 방식 선택 모달 창 UI 및 기능 구현
  fe/src/App.jsx
  fe/src/components/Cart/Cart.jsx
  fe/src/components/Cart/CartLists.jsx
  fe/src/components/Menu/MenuItem.jsx
  fe/src/components/Menu/MenuList.jsx
  fe/src/components/Modal/Cancel/Cancel.jsx
  fe/src/components/Modal/Dim/Dim.module.css
  fe/src/components/Modal/Menu/Decision/Decision.jsx
  fe/src/components/Modal/Menu/MenuModal.jsx
  fe/src/components/Modal/Menu/MenuModal.module.css
  fe/src/components/Modal/Payment/PaymentModal.jsx
  fe/src/components/Modal/Payment/PaymentModal.module.css
Labels: front-end, feat, design

#41 [be] docs: API 문서 업데이트
  openAPI.yml
Labels: back-end, docs

#43 [fe] feat: 종합 결제 기능 구현
  fe/.eslintrc.json
  fe/src/App.jsx
  fe/src/components/Cart/Cart.jsx
  fe/src/components/Cart/Cart.module.css
  fe/src/components/Cart/Timer.jsx
  fe/src/components/Cart/Timer.module.css
  fe/src/components/CategoryTab/CategoryTab.jsx
  fe/src/components/CategoryTab/CategoryTab.module.css
  fe/src/components/Loading/Loading.jsx
  fe/src/components/Loading/Loading.module.css
  fe/src/components/Menu/MenuItem.jsx
  fe/src/components/Menu/MenuList.jsx
  fe/src/components/Menu/MenuList.module.css
  fe/src/components/Modal/Dim/Dim.jsx
  fe/src/components/Modal/Dim/Dim.module.css
  fe/src/components/Modal/Menu/Decision/Decision.jsx
  fe/src/components/Modal/Menu/Info/Info.jsx
  fe/src/components/Modal/Menu/Info/Info.module.css
  fe/src/components/Modal/Menu/MenuModal.jsx
  fe/src/components/Modal/Menu/MenuModal.module.css
  fe/src/components/Modal/Payment/CashModal.jsx
  fe/src/components/Modal/Payment/CashModal.module.css
  fe/src/components/Modal/Payment/PaymentModal.jsx
  fe/src/components/Recipe/Recipe.jsx
  fe/src/mocks/data/coffee.js
  fe/src/mocks/data/decaffein.js
  fe/src/mocks/data/juice.js
  fe/src/mocks/data/latte.js
  fe/src/mocks/data/recipe.js
  fe/src/mocks/data/tea.js
  fe/src/mocks/handlers.js
Labels: front-end, feat, design, refactor

#40 [be] feat: 음료 목록 조회 기능 구현
  kiosk-be/src/main/java/team04/kioskbe/Drink/DrinkController.java
  kiosk-be/src/main/java/team04/kioskbe/Drink/DrinkRepository.java
  kiosk-be/src/main/java/team04/kioskbe/Drink/DrinkResponse.java
  kiosk-be/src/main/java/team04/kioskbe/Drink/DrinkService.java
  kiosk-be/src/main/java/team04/kioskbe/Drink/OptionResponse.java
  kiosk-be/src/main/java/team04/kioskbe/Drink/OptionValue.java
  kiosk-be/src/main/java/team04/kioskbe/domain/Category.java
  kiosk-be/src/main/java/team04/kioskbe/domain/Drink.java
  kiosk-be/src/main/java/team04/kioskbe/domain/Option.java
  kiosk-be/src/test/java/team04/kioskbe/Drink/DrinkRepositoryTest.java
  kiosk-be/src/test/java/team04/kioskbe/Drink/DrinkServiceTest.java
Labels: back-end, feat

#46 [fe] refactor: 프론트엔드 리팩토링
  fe/.eslintrc.json
  fe/.prettierrc
  fe/src/App.jsx
  fe/src/App.module.css
  fe/src/components/Cart/Cart.jsx
  fe/src/components/Cart/Cart.module.css
  fe/src/components/Cart/CartItem.module.css
  fe/src/components/Cart/CartLists.module.css
  fe/src/components/Cart/Timer.module.css
  fe/src/components/CategoryTab/CategoryTab.jsx
  fe/src/components/CategoryTab/CategoryTab.module.css
  fe/src/components/Loading/Loading.jsx
  fe/src/components/Loading/Loading.module.css
  fe/src/components/Menu/MenuItem.module.css
  fe/src/components/Menu/MenuList.jsx
  fe/src/components/Menu/MenuList.module.css
  fe/src/components/Modal/Dim/Dim.jsx
  fe/src/components/Modal/Dim/Dim.module.css
  fe/src/components/Modal/Menu/Decision/Decision.jsx
  fe/src/components/Modal/Menu/Decision/Decision.module.css
  fe/src/components/Modal/Menu/Info/Info.jsx
  fe/src/components/Modal/Menu/Info/Info.module.css
  fe/src/components/Modal/Menu/MenuModal.jsx
  fe/src/components/Modal/Menu/MenuModal.module.css
  fe/src/components/Modal/Payment/CashModal.jsx
  fe/src/components/Modal/Payment/CashModal.module.css
  fe/src/components/Recipe/Recipe.jsx
  fe/src/components/Recipe/Recipe.module.css
  fe/src/mocks/data/coffee.js
  fe/src/mocks/data/decaffein.js
  fe/src/mocks/data/juice.js
  fe/src/mocks/data/latte.js
  fe/src/mocks/data/tea.js
Labels: front-end, feat, design, refactor

#49 [fe] 리팩토링 및 url 수정
  fe/src/App.jsx
  fe/src/App.module.css
  fe/src/components/Cart/Cart.jsx
  fe/src/components/Cart/CartItem.module.css
  fe/src/components/Cart/CartLists.module.css
  fe/src/components/Menu/MenuList.jsx
  fe/src/components/Menu/MenuList.module.css
  fe/src/components/Modal/Payment/CashModal.jsx
  fe/src/components/Modal/Payment/PaymentModal.jsx
  fe/src/components/Recipe/Recipe.jsx
  fe/src/components/Recipe/Recipe.module.css
  fe/src/mocks/handlers.js
Labels: front-end, fix, refactor

#50 [fe] feat: 현금 결제 영수증 데이터 서버 연결
  fe/src/App.jsx
  fe/src/components/Cart/Cart.jsx
  fe/src/components/Modal/Payment/CashModal.jsx
  fe/src/components/Recipe/Recipe.jsx
  fe/src/components/Recipe/Recipe.module.css
  fe/src/index.jsx
Labels: front-end, feat

#52 [fe] feat: 인기 메뉴 표시 기능
  fe/src/components/Menu/MenuItem.jsx
  fe/src/components/Menu/MenuItem.module.css
  fe/src/components/Menu/MenuList.jsx
Labels: feat

#57 [fe] feat: 카드 결제 관련 작업
  fe/public/index.html
  fe/src/App.jsx
  fe/src/App.module.css
  fe/src/components/Cart/Cart.jsx
  fe/src/components/Cart/Cart.module.css
  fe/src/components/Menu/MenuItem.jsx
  fe/src/components/Menu/MenuList.jsx
  fe/src/components/Modal/Cancel/Cancel.jsx
  fe/src/components/Modal/ErrorMessage/ErrorMessage.jsx
  fe/src/components/Modal/ErrorMessage/ErrorMessage.module.css
  fe/src/components/Modal/Menu/Decision/Decision.jsx
  fe/src/components/Modal/Menu/MenuModal.jsx
  fe/src/components/Modal/Payment/CashModal.jsx
  fe/src/components/Modal/Payment/PaymentModal.jsx
  fe/src/components/Recipe/Recipe.jsx
Labels: front-end, feat
